### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by ricardobarroslourenco** [Atcold/SP19-DL-collaborative-notes#104]
Hi @Atcold ! As I have mentioned on twitter, I am interested in translating these notes to Portuguese, since we have a growing community of DL in Brazil. 

I would like to know how this can be arranged, and which Creative Commons license you wish to apply to it.

Best regards,
Ricardo

**Comment by Atcold** [comment]
The first week of notes will appear by Sunday (for Monday's class) and Monday (for Tuesday's class).
Next week content from the previous week may be revised, in order to add cross references, fix typos, and so on. So, I'd wait one week before starting with the translation.

Also, given that you'll be reading the English version, do fix typos and formatting issues.
If content issues are found, point them out to me.

I will have to look into "which" Creative Commons license to apply. Something mainstream? Suggestions?

**Comment by ricardobarroslourenco** [comment]
> The first week of notes will appear by Sunday (for Monday's class) and Monday (for Tuesday's class).
> Next week content from the previous week may be revised, in order to add cross references, fix typos, and so on. So, I'd wait one week before starting with the translation.

Nice. I can always ask and see if those are _stable_.

> Also, given that you'll be reading the English version, do fix typos and formatting issues.
> If content issues are found, point them out to me.

Happy to help :) 

> I will have to look into "which" Creative Commons license to apply. Something mainstream? Suggestions?

I would think about something like [Attribution-NonCommercial-ShareAlike (CC BY-NC-SA)](https://creativecommons.org/use-remix/cc-licenses/#by-nc-sa)

**Comment by ricardobarroslourenco** [comment]
@Atcold I'll close the issue here since the translation will be ongoing at https://github.com/Atcold/DLSP20-collaborative-notes

**Comment by ricardobarroslourenco** [comment]
Hi @Atcold ! I would like to know if this repository would also be licensed as CC BY-NC-SA as well. Another thing is regarding the [2020 repo](https://github.com/Atcold/pytorch-Deep-Learning-Minicourse),  which has both a codebase and text. What would be their licenses?

**Comment by Atcold** [comment]
[Yann mentioned](https://twitter.com/ylecun/status/1222175914777292801) Creative Common.
Feel free to send a PR there as well with a CC BY-NC-SA license.
